version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      timezone: Asia/Tokyo
      time: "12:00"
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      timezone: Asia/Tokyo
      time: "12:00"
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad
    groups:
      npm:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: '/api/'
    schedule:
      interval: daily
      timezone: Asia/Tokyo
      time: "12:00"
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad
    groups:
      api:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: '/front/'
    schedule:
      interval: daily
      timezone: Asia/Tokyo
      time: "12:00"
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad
    groups:
      front:
        patterns:
          - "*"
